class User:
    def __init__(self, name, email):
        self.name = name
        self.email = email

    def __eq__(self, other):
        return self.email == other.email


class UserForm(User):
    def validate_name(self):
        if self.name[0] not in [
            "_",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "q",
            "w",
            "r",
            "t",
            "y",
            "u",
            "i",
            "o",
            "p",
            "s",
            "h",
            "j",
            "k",
            "l",
            "z",
            "x",
            "v",
            "n",
            "m",
        ]:
            return ValueError
        if self.name[-1] not in [
            "_",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "q",
            "w",
            "r",
            "t",
            "y",
            "u",
            "i",
            "o",
            "p",
            "s",
            "h",
            "j",
            "k",
            "l",
            "z",
            "x",
            "v",
            "n",
            "m",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
        ]:
            return ValueError
        slice = self.name[1:-2]
        for x in slice:
            if x not in [
                "_",
                ".",
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "q",
                "w",
                "r",
                "t",
                "y",
                "u",
                "i",
                "o",
                "p",
                "s",
                "h",
                "j",
                "k",
                "l",
                "z",
                "x",
                "v",
                "n",
                "m",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
            ]:
                return ValueError
        else:
            return self

    def validate_email(self):
        lisemail = self.email.split("@")
        login = lisemail[0]
        domain = lisemail[1]
        if login[0] not in [
            "_",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "q",
            "w",
            "r",
            "t",
            "y",
            "u",
            "i",
            "o",
            "p",
            "s",
            "h",
            "j",
            "k",
            "l",
            "z",
            "x",
            "v",
            "n",
            "m",
        ]:
            return ValueError
        if login[-1] not in [
            "_",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "q",
            "w",
            "r",
            "t",
            "y",
            "u",
            "i",
            "o",
            "p",
            "s",
            "h",
            "j",
            "k",
            "l",
            "z",
            "x",
            "v",
            "n",
            "m",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
        ]:
            return ValueError
        slice = self.name[1:-2]
        for x in slice:
            if x not in [
                "_",
                ".",
                "+",
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "q",
                "w",
                "r",
                "t",
                "y",
                "u",
                "i",
                "o",
                "p",
                "s",
                "h",
                "j",
                "k",
                "l",
                "z",
                "x",
                "v",
                "n",
                "m",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
            ]:
                return ValueError
        if domain[0] not in [
            "_",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "q",
            "w",
            "r",
            "t",
            "y",
            "u",
            "i",
            "o",
            "p",
            "s",
            "h",
            "j",
            "k",
            "l",
            "z",
            "x",
            "v",
            "n",
            "m",
        ]:
            return ValueError
        if domain[-1] not in [
            "_",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "q",
            "w",
            "r",
            "t",
            "y",
            "u",
            "i",
            "o",
            "p",
            "s",
            "h",
            "j",
            "k",
            "l",
            "z",
            "x",
            "v",
            "n",
            "m",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
        ]:
            return ValueError
        slice = self.name[1:-2]
        for x in slice:
            if x not in [
                "_",
                ".",
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "q",
                "w",
                "r",
                "t",
                "y",
                "u",
                "i",
                "o",
                "p",
                "s",
                "h",
                "j",
                "k",
                "l",
                "z",
                "x",
                "v",
                "n",
                "m",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
            ]:
                return ValueError
        else:
            return self
